#!/bin/sh
# wrapper script for apg to use my custom settings
MODE="SNCL"
LEN=10
if [ "$1" = "-nospecial" ]
then
  MODE="NCL"
elif [ -n "$1" ]
then
  LEN="$1"
fi

exec /usr/local/bin/apg -n 8 -m $LEN -x $LEN -l -M $MODE -t \
	-E \[\]\(\)\#!@%^\*\<\>\?\/,.\`\~\{\}\;\"\'-_=+\:\\\|\&
